version: "3"

services:
  nodejs-app:
    image: personal-task-management-api-image
    build:
      context: .
      args:
        APP_PORT: 3000
        ENV_FILE: .env.prod
    command: ["node", "app.js"]